### PR TITLE
disable keyboardTracking for the frequency input

### PR DESCRIPTION
**Pull request by boryszef**
Fix the problem, when the number is filled with decimal zeros before the user has finished typing.

### CODE REVIEW

**Comment by boryszef** [comment]
fix #378 #529 #448 #588

**Comment by ikbenkous** [comment]
This change works on my end and works with #626!

**Review by ea4k — CHANGES_REQUESTED** [review]
Github warns that there are conflicts that need to be fixed before merge.

**Comment by boryszef** [comment]
Another change was merged recently, increasing the precision of the frequency. I have confirmed locally that both changes work together and resolved the conflict accordingly.

**Comment by ikbenkous** [comment]
@ea4k I believe CI on the master branch broke because of some unrelated merges you did recently. That's probably why this PR is failing checks as well.

Are you aware of that? Or am I mistaken?

[ccb1850](https://github.com/ea4k/klog/pull/617/commits/ccb18503a6f2f731be2cf0ed2bfbdcdde9772ece) was green across the board.

**Comment by ea4k** [comment]
I merged several PR and code I had in my computer. 
I didn't want all branches to be too far from each other and I decided to merge.

It was not usual that I had several PR waiting and my time for coding since August has been too short to finish the work I was doing.

The code in master is not finished but I wanted it to be available.

**Comment by ikbenkous** [comment]
@boryszef I fixed CI on master. You might be able to rebase these commits and retest them out with CI.

**Comment by ikbenkous** [comment]
This stale PR can now be closed. Changes already merged in #637.

Could we close this one? @ea4k or @boryszef ...

**Pull request closed without merging**
