### PR TITLE
Closing #575, #578, #577

### PR DESCRIPTION
**Pull request by ea5wa**
Connection between Satellites Tab and MainWindow was emptying the BandComboBox

### CODE REVIEW

**Comment by ea5wa** [comment]
This commit solves Issue 575

**Comment by ea5wa** [comment]
Added a second commit to solve Issue 578 (logWindow refresh after importing ADIF)

**Comment by ea5wa** [comment]
Added a third commit to solve Issue 577 (QRPP as valid suffix)_

**Comment by ea4k** [comment]
Closed by PR: https://github.com/ea4k/klog/pull/579

**Pull request merged**
