### PR TITLE
Updated Czech Translation

### PR DESCRIPTION
**Pull request by foldynl**
I am sending you an updated czech translation file.

### CODE REVIEW

**Comment by ea4k** [comment]
Thank you!

**Comment by ea4k** [comment]
As you are usually sending PR, just for your info.
When a release brings an updated translation, I also write it in the Changelog. ;-)

**Comment by foldynl** [comment]
If I understand you correctly if a translation is sent then I should update the Changelog, correct? I'm not sure if it's good to write the Changelog because:
1) the Changelog would become a source of merging conflicts
2) From non-maintainer perspective, it is not possible to say whether the PR will be accepted and especially to which release will be merged.

It's about your comfort, what's better for you. To write the Changelog for every translation update or leave it on maintainer ?

**Comment by ea4k** [comment]
Thanks for the answer,
The suggestion for you to update the Changelog is to ensure that your contribution is reflected in the Changelog. I usually update it but just in case I forgot :-)
(I should not, by the way) :-)
Thank you!

**Pull request merged**
